[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --flash-mode dio --flash-size 8mb --flash-freq 80mhz"

[env]
ESP_LOGLEVEL="DEBUG"

[build]
rustflags = [
  # "-C", "link-arg=-Tlinkall.x", # Already included in the workspace .cargo/config.toml

  "-C", "link-arg=-Trom_functions.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
